{{- $releaseName := .Release.Name -}}
{{- $chartName := include "osmdbt-wrapper.name" . -}}
{{- $cloudProviderFlavor := include "osmdbt-wrapper.cloudProviderFlavor" . -}}
{{- $cloudProviderDockerRegistryUrl := include "osmdbt-wrapper.cloudProviderDockerRegistryUrl" . -}}
{{- $tag := include "osmdbt-wrapper.tag" . -}}
{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $releaseName }}-{{ $chartName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "osmdbt-wrapper.environment" . }}
    release: {{ $releaseName }}
    {{- include "osmdbt-wrapper.labels" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $chartName }}
      release: {{ $releaseName }}
      run: {{ $releaseName }}-{{ $chartName }}
  template:
    metadata:
      labels:
        app: {{ $chartName }}
        release: {{ $releaseName }}
        run: {{ $releaseName }}-{{ $chartName }}
      {{- with .Values.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ $releaseName }}-{{ $chartName }}-deployment
          {{- with .Values.image }}
          {{- if ne $cloudProviderFlavor "minikube" }}
          image: {{ $cloudProviderDockerRegistryUrl }}/{{ .repository }}:{{ $tag }}
          {{- else }}
          image: {{ .repository }}:{{ $tag }}
          {{- end }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ $releaseName }}-{{ $chartName }}-configmap
            - configMapRef:
                name: {{ $releaseName }}-{{ $chartName }}-arstotzka-configmap
            {{- if and .Values.arstotzka.enabled .Values.arstotzka.networkCM }}
            - configMapRef:
                name: {{ .Values.arstotzka.networkCM }}
            {{- end }}
            - secretRef:
                name: {{ $releaseName }}-{{ $chartName }}-secret
          {{- if .Values.resources.enabled }}
          resources:
            {{- toYaml .Values.resources.value | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: osmdbt-config
              mountPath: /osmdbt/config
            {{- if .Values.dbConfig.sslAuth.enabled }}
            - name: cert-conf
              mountPath: {{ .Values.dbConfig.sslAuth.mountPath }}
            {{- end }}
      volumes:
        - name: osmdbt-config
          configMap:
            name: {{ $releaseName }}-{{ $chartName }}-osmdbt-configmap
        {{- if .Values.dbConfig.sslAuth.enabled }}
        - name: cert-conf
          secret:
            secretName: {{ .Values.dbConfig.sslAuth.secretName }}
        {{- end }}
      restartPolicy: Always
{{- end -}}
